config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :searches do
    collection do
      get :analytics
    end
  end


  root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
# app/models/article.rb
class Article < ApplicationRecord
  def self.search(search)
    if search.present?
      where('LOWER(title) LIKE ?', "%#{search.downcase}%")
    else
      all
    end
  end
end

app/models/search.rb
class Search < ApplicationRecord
  validates :query, presence: true, length: { minimum: 2, tokenizer: ->(str) { str.split(/\s+/) } }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  def index
  @query = params[:search]
  @articles = Article.search(@query)

  # Check if the query is valid
  if @query.present? && @query.split(/\s+/).length >= 2
    @search = Search.find_or_create_by(query: @query)
    @search.increment!(:count)
    
  end
end


  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

   def show
   end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy!

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :content)
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def analytics
  @searches = Search.order(count: :desc)
  end

  def create
      @search = Search.create(search_params)
      redirect_to @search

  end

  def show
    @search = Search.find(params[:id])
  end

  private

  def search_params
    params.require(:search).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= article.content %>
  </p>

</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<p class="notice"><%= notice %></p>
<h1 class="page-title">Articles</h1>
<%= link_to 'Search Analytics', analytics_searches_path, class: 'search-analytics-link' %>
<%= link_to 'New Article', new_article_path, class: 'new-article-link' %>

<div class="search-form">
  <%= form_tag articles_path, method: :get, id: 'search_form' do %>
    <%= text_field_tag :search, params[:search], id: 'searchInput', placeholder: 'Search articles...', class: 'search-input' %>
    <%= submit_tag 'Search', class: 'search-btn' %>
  <% end %>
</div>

<div class="article-list">
  <% @articles.each do |article| %>
    <div class="article-item">
      <%= render article %>
      <p><%= link_to "Show this article", article %></p>
    </div>
  <% end %>
</div>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>

  <%= button_to "Destroy this article", @article, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RealtimeSearchAnalytics</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/searches/analytics.html.erb
<h1>Search Analytics</h1>

<div class="back-link">
  <%= link_to 'Back to Home', root_path %>
</div>

<% if @searches.empty? %>
  <p class="no-searches">No valid searches found.</p>
<% else %>
  <table class="search-table">
    <thead>
      <tr>
        <th>Query</th>
        <th>No of searches</th>
      </tr>
    </thead>
    <tbody>
      <% @searches.each do |search| %>
        <tr>
          <td><%= search.query %></td>
          <td><%= search.count %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>